[tool.poetry]
name = "stackspot-ai"
version = "0.1.0"
description = ""
authors = ["engeziellithon <engeziellithonvieira@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
